// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5H3Y6ULe8-jtsA_w54d3HRAxgC08Y9iA',
    appId: '1:1015336484850:web:8438a3443a6891099ff56b',
    messagingSenderId: '1015336484850',
    projectId: 'listify-b92aa',
    authDomain: 'listify-b92aa.firebaseapp.com',
    storageBucket: 'listify-b92aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCPK8PSUYpHRePyXi3_rp4Wqg2Va5y69s',
    appId: '1:1015336484850:android:2b52fed6848645829ff56b',
    messagingSenderId: '1015336484850',
    projectId: 'listify-b92aa',
    storageBucket: 'listify-b92aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ95ImlB_Jy0c_p8IAgm57DzBLADNBfYM',
    appId: '1:1015336484850:ios:b3180f317303694e9ff56b',
    messagingSenderId: '1015336484850',
    projectId: 'listify-b92aa',
    storageBucket: 'listify-b92aa.firebasestorage.app',
    iosBundleId: 'com.example.listify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ95ImlB_Jy0c_p8IAgm57DzBLADNBfYM',
    appId: '1:1015336484850:ios:b3180f317303694e9ff56b',
    messagingSenderId: '1015336484850',
    projectId: 'listify-b92aa',
    storageBucket: 'listify-b92aa.firebasestorage.app',
    iosBundleId: 'com.example.listify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5H3Y6ULe8-jtsA_w54d3HRAxgC08Y9iA',
    appId: '1:1015336484850:web:2f69fafcda8ae73f9ff56b',
    messagingSenderId: '1015336484850',
    projectId: 'listify-b92aa',
    authDomain: 'listify-b92aa.firebaseapp.com',
    storageBucket: 'listify-b92aa.firebasestorage.app',
  );
}
